# Generated by Django 4.2.2 on 2023-06-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_aboutus_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammemeber',
            name='discriptions',
        ),
    ]
