# Generated by Django 4.2.2 on 2023-06-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_slider_options_slider_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image1',
            field=models.ImageField(default=1, upload_to='aboutimage/'),
            preserve_default=False,
        ),
    ]
