# Generated by Django 4.2.2 on 2023-06-30 05:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_aboutus_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagingDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mdimage/')),
                ('message', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
