# Generated by Django 4.2.2 on 2023-06-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_managingdirector'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemeber',
            name='fbUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammemeber',
            name='instaUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammemeber',
            name='twUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
