# Generated by Django 4.2.2 on 2023-06-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_teammemeber_fburl_teammemeber_instaurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemeber',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
