# Generated by Django 4.2.2 on 2023-07-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_teammemeber_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tel_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
