# Generated by Django 4.2.2 on 2023-07-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contact_tel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquery',
            name='subject',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
