# Generated by Django 4.2.2 on 2023-07-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customerquery_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=150, null=True)),
                ('video_url', models.URLField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
