# Generated by Django 4.2.2 on 2023-07-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contact_fburl_contact_instaurl_contact_twurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ubUrl',
            new_name='ybUrl',
        ),
    ]
