# Generated by Django 4.2.2 on 2023-07-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_slider_options_slider_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='managingdirector',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managingdirector',
            name='position',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
